package com.neverEngineLabs.GML2019;


import java.io.File;

// Public Interface for handling asynchronous Callback generated by PApplet

public interface FileSelectionHandler {

    void onFileSelected(File f);

}
